# Generated by Django 2.2.13 on 2020-12-17 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bonds", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="bond",
        ),
        migrations.AddField(
            model_name="bond",
            name="bond_owner",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
